Bootstrap CSS to Tailwind CSS
Chameleon-company/Chameleon-Website pull request #107
Opened 2023-11-25 09:49 UTC by kaseyuu

Migrate from Bootstrap CSS to Tailwind CSS for Login page.

2023-11-25 11:46 UTC, mukundnivas requested changes
This seems to be the same issue from PR #105. Please refer to it.

2023-11-25 11:46 UTC, mukundnivas commented on front_end_project/src/pages/login/login.js
Hey Kasey,

This seems to be the same issue from PR #105. Please refer to it.

The Login page still seems to contain all the React-bootstrap higher order classes. I could you have refactored couple of class names to Tailwind supported ones. The requirement here to scratch all the React-bootstrap's higher-order classes like "Button" etc to Tailwind CSS's utility classes.

2023-11-25 11:59 UTC, kaseyuu commented on front_end_project/src/pages/login/login.js
Hi Mukund, just to confirm, do you expect us to completely remove React Bootstrap and replace it with HTML+Tailwind CSS?

2023-11-25 14:24 UTC, mukundnivas commented on front_end_project/src/pages/login/login.js
Yes @kaseyuu porting over to Tailwind means porting all the components to utility based classes from Tailwind CSS.

2023-11-26 00:23 UTC, mukundnivas commented
As discussed, please port all the components of the page to Tailwind CSS.

2023-11-26 00:23 UTC, closed without merging